theme: jekyll-theme-minimal

title: Mamba Documentation
description: You can find the documentation of the Mamba Language here. For the page of the repository itself check out https://joelabrahams.nl/mamba/

logo: /image/logo_medium.png
